In [ ]:
import numpy as np


1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
vector = np.arange(1, 11)
print("Вектор з першими 10 натуральними числами:", vector)

Вектор з першими 10 натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
matrix_zeros = np.zeros((3, 3))
print("Матриця розміром 3x3 з нулями:\n", matrix_zeros)

Матриця розміром 3x3 з нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
matrix_random_integers = np.random.randint(1, 11, size=(5, 5))
print("Масив розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 10:\n", matrix_random_integers)


Масив розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 10:
 [[ 2  9  2  6  6]
 [ 6  7  9  3  6]
 [ 1  4  3 10  1]
 [ 6  5  4  6  9]
 [ 8  9  3  7  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [ ]:
matrix_random_floats = np.random.rand(4, 4)
print("Масив розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1:\n", matrix_random_floats)


Масив розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1:
 [[0.45007067 0.55643056 0.47654762 0.62338219]
 [0.51698374 0.53412619 0.70871259 0.42404819]
 [0.07106397 0.0585422  0.79903258 0.57805069]
 [0.02952807 0.12785507 0.01966406 0.65199231]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [ ]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("Перший масив:", array1)
print("Другий масив:", array2)
print("Додавання елементів двох масивів:", np.add(array1, array2))
print("Віднімання елементів другого выд першого масива:", np.subtract(array1, array2))
print("Множення елементів двох масивів:", np.multiply(array1, array2))


Перший масив: [ 2  7 10  5 10]
Другий масив: [ 4 10  5  9  5]
Додавання елементів двох масивів: [ 6 17 15 14 15]
Віднімання елементів двох масивів: [-2 -3  5 -4  5]
Множення елементів двох масивів: [ 8 70 50 45 50]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector1 = np.random.randint(1, 11, size=7)
vector2 = np.random.randint(1, 11, size=7)
scalar_product = np.dot(vector1, vector2)
print("Вектор №1: ", vector1)
print("Вектор №2: ", vector2)
print("Скалярний добуток двох векторів:", scalar_product)

Вектор №1:  [7 6 3 8 2 5 3]
Вектор №2:  [ 1  5  8  3 10  6  3]
Скалярний добуток двох векторів: 144


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)
matrix_product = np.dot(matrix1, matrix2)
print("Добуток двох матриць:\n", matrix_product)

Матриця 1:
 [[ 6  9]
 [ 2 10]]
Матриця 2:
 [[10  6  9]
 [10  1  2]]
Добуток двох матриць:
 [[150  45  72]
 [120  22  38]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [ ]:
matrix3 = np.random.randint(1, 11, size=(3, 3))
print("Вихыдна матриця:\n", matrix3)
inverse_matrix = np.linalg.inv(matrix3)
print("Обернена матриця:\n", inverse_matrix)

Вихыдна матриця:
 [[ 5  3  6]
 [ 4  5  6]
 [ 3 10  9]]
Обернена матриця:
 [[-0.71428571  1.57142857 -0.57142857]
 [-0.85714286  1.28571429 -0.28571429]
 [ 1.19047619 -1.95238095  0.61904762]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [ ]:
matrix4 = np.random.rand(4, 4)
print("Вихыдна матриця:\n", matrix4)
transposed_matrix = np.transpose(matrix4)
print("Транспонована матриця:\n", transposed_matrix)

Вихыдна матриця:
 [[0.50396939 0.95811293 0.94332505 0.23916348]
 [0.70270749 0.71826387 0.4788463  0.03774854]
 [0.43977904 0.03203489 0.32507475 0.07453504]
 [0.06731804 0.5795253  0.98682134 0.58858896]]
Транспонована матриця:
 [[0.50396939 0.70270749 0.43977904 0.06731804]
 [0.95811293 0.71826387 0.03203489 0.5795253 ]
 [0.94332505 0.4788463  0.32507475 0.98682134]
 [0.23916348 0.03774854 0.07453504 0.58858896]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [ ]:
matrix5 = np.random.randint(1, 11, size=(3, 4))
print("Матриця:\n", matrix5)
vector3 = np.random.randint(1, 11, size=4)
print("Вектор::\n", vector3)
matrix_vector_product = np.dot(matrix5, vector3)
print("Добуток матриці на вектор::\n", matrix_vector_product)

Матриця:
 [[ 8  6  7  9]
 [10  4  3  9]
 [ 1  6 10  8]]
Вектор::
 [7 4 7 2]
Добуток матриці на вектор: [147 125 117]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.


In [ ]:
matrix6 = np.random.rand(2, 3)
vector4 = np.random.rand(3)
matrix_vector_product = np.dot(matrix6, vector4)
print("Добуток матриці на вектор:", matrix_vector_product)


Добуток матриці на вектор: [1.06481667 0.88055555]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix7 = np.random.randint(1, 11, size=(2, 2))
matrix8 = np.random.randint(1, 11, size=(2, 2))
elementwise_product = np.multiply(matrix7, matrix8)
print("Поелементне множення двох матриць:\n", elementwise_product)

Поелементне множення двох матриць:
 [[ 4 15]
 [40 25]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


In [ ]:
matrix9 = np.random.randint(1, 11, size=(2, 2))
matrix10 = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.dot(matrix9, matrix10)
print("Добуток двох матриць:\n", matrix_product)

Добуток двох матриць:
 [[ 31 163]
 [ 23 104]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [ ]:
matrix11 = np.random.randint(1, 101, size=(5, 5))
matrix_sum = np.sum(matrix11)
print("Сума елементів матриці:", matrix_sum)


Сума елементів матриці: 1248


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [ ]:
matrix12 = np.random.randint(1, 11, size=(4, 4))
matrix13 = np.random.randint(1, 11, size=(4, 4))
matrix_difference = np.subtract(matrix12, matrix13)
print("Різниця двох матриць:\n", matrix_difference)

Різниця двох матриць:
 [[ 2  3  2  5]
 [ 2  4  5 -2]
 [ 4  0  0  5]
 [ 7  5 -3  0]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [ ]:
matrix14 = np.random.rand(3, 3)
row_sums = np.sum(matrix14, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("Вектор-стовпчик з сумами елементів кожного рядка матриці:\n", column_vector)


Вектор-стовпчик з сумами елементів кожного рядка матриці:
 [[1.44894189]
 [1.79510875]
 [1.44281501]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [ ]:
matrix15 = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix15)
print("Матриця з квадратами чисел початкової матриці:\n", squared_matrix)

Матриця з квадратами чисел початкової матриці:
 [[ 9  1 36  9]
 [64 36 81 16]
 [ 4 36 49  1]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [ ]:
vector5 = np.random.randint(1, 51, size=4)
square_root_vector = np.sqrt(vector5)
print("Вектор з квадратними коренями чисел початкового вектора:", square_root_vector)

Вектор з квадратними коренями чисел початкового вектора: [4.35889894 2.44948974 6.63324958 3.46410162]
